### ISSUE TITLE
Create the list view

### ISSUE THREAD

**Issue by martekn** [martekn/bidquest#49]
### Tasks

- [ ] Display search results
- [ ] Display results from all auctions
- [ ] Display results from auctions based on category
- [ ] Sort results

### This fulfills the following user stories:
- An unregistered user may search through Listings
