### ISSUE TITLE
Create profile page

### ISSUE THREAD

**Issue by martekn** [martekn/bidquest#59]
### Tasks
- [x] Display user information
- [x] Allow users to add a new image as their avatar
- [x] Allow users to edit the url or alt text of current avatar
- [x] Allow users to remove avatar    

### This fulfills the following user stories:

- A registered user may update their avatar
