### ISSUE TITLE
Create the auction form view

### ISSUE THREAD

**Issue by martekn** [martekn/bidquest#61]
### Tasks

- [x] Allow registered users to create an auction
- [x] Allow registered users to edit their own auctions
- [x] Allow registered users to delete their own auction

### This fulfills the following user stories:
- A registered user may create a Listing with a title, deadline date, media gallery and description
